spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eodaego}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp-millis: 3600000
